spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/g_37_jp_shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: qwerty007
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
key:
  access: aovKvB5EPC2sJF8M1vW08teR3cjH8UeqgbCLRSz1vO0=
  refresh: ootDucfsr8xxJcQLIXcEdMeFEp2Y4hcmSmSQb83o1Vg=